name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  buildJob:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.11-dev
        uses: actions/setup-python@v5
        with:
          python-version: '3.11-dev'

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version

      - name: Verify Python Environment
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip list
          python3 -m pip show setuptools

      - name: Build FFmpeg with Swift Package
        run: |
          cd ${{ github.workspace }}  # Ensure we are in the GitHub Actions workspace
          swift build --disable-sandbox BuildFFmpeg enable-gmp enable-nettle enable-libsmbclient
