name: Build and Export XCFrameworks

on:
  push:
    branches:
      - main

jobs:
  export_xcframeworks:
    name: Export XCFrameworks
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version
      - name: Setup Python
        run: |
          brew install python-setuptools
      - name: Export XCFrameworks
        run: |
          swift package --disable-sandbox BuildFFmpeg
          mkdir -p output
          mv *.xcframework output/
      - name: Upload XCFrameworks
        uses: actions/upload-artifact@v2
        with:
          name: xcframeworks
          path: output/*.xcframework
