name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  buildJob:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python 3.11-dev
        uses: actions/setup-python@v5
        with:
          python-version: '3.11-dev'

      - name: Install Python 3 with Development Headers
        run: |
          brew update
          brew install python@3.11  # Install Python 3.11 using Homebrew
          brew link --overwrite python@3.11

      - name: Install Build Tools and Libraries
        run: |
          brew install pkg-config # Install pkg-config which is often needed for building libraries

      - name: Set Up Python Virtual Environment
        run: |
          python3 -m venv venv  # Create a virtual environment
          source venv/bin/activate  # Activate the virtual environment
          python3 -m pip install --upgrade pip setuptools wheel  # Upgrade pip, setuptools, wheel

      - name: Verify Python Environment
        run: |
          source venv/bin/activate  # Activate the virtual environment
          python3 --version
          python3 -m pip list
          python3 -m pip show setuptools

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version

      - name: Build FFmpeg with Swift Package
        run: |
          cd ${{ github.workspace }}  # Ensure we are in the GitHub Actions workspace
          source venv/bin/activate  # Activate the virtual environment
          swift package --disable-sandbox BuildFFmpeg enable-libsmbclient notRecompile

      - name: Upload Config Log
        if: failure() # Only upload log if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: config-log
          path: /Users/runner/work/FFmpegKit/FFmpegKit/.Script/libsmbclient-samba-4.15.13/bin/config.log
