name: Build and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  buildJob:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2 # Correct syntax to checkout code
        with:
          submodules: true

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version

      - name: Install Python 3.10 with Development Headers
        run: |
          brew update
          brew install python@3.10  # Installs Python 3.10 with development headers
          brew link --overwrite python@3.10
          echo 'export PATH="/usr/local/opt/python@3.10/bin:$PATH"' >> $GITHUB_ENV

      - name: Ensure Python Development Tools
        run: |
          # Set up environment variables to ensure proper build configuration
          export PATH="/usr/local/opt/python@3.10/bin:$PATH"
          export LDFLAGS="-L/usr/local/opt/python@3.10/lib"
          export CPPFLAGS="-I/usr/local/opt/python@3.10/include"
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade setuptools

      - name: Build FFmpeg with Swift Package
        run: |
          cd ${{ github.workspace }}  # Ensure we are in the GitHub Actions workspace
          swift package --disable-sandbox BuildFFmpeg enable-gmp enable-nettle enable-libsmbclient  # Replace with the actual Swift build command
