name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  buidJoB:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v2 # Correct syntax to checkout code
        with:
          submodules: true

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version

      - name: Ensure Python 3.10 is Installed
        run: |
          # Ensure Python 3.10 is installed with development headers
          brew install python@3.10
          brew link --overwrite python@3.10

      - name: Set Environment Variables for Python and Xcode
        run: |
          export PATH="/usr/local/opt/python@3.10/bin:$PATH"
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | cut -d '.' -f 1,2)

      - name: Build FFmpeg with Swift Package
        run: |
          cd ${{ github.workspace }}  # Ensure we are in the GitHub Actions workspace
          swift package BuildFFmpeg platforms=ios,isimulator,tvos,tvsimulator notRecompile
